services:
  flow-log:
    container_name: flow-log
    image: ${REPOSITORY}/flow-log:${FLOW_VERSION}
    restart: unless-stopped
    hostname: flow.log
    networks:
      - flow
      - traefik
    environment:
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.Flow-Log.entrypoints=https
      - traefik.http.routers.Flow-Log.rule=PathPrefix(`/api/log`) && Host(`${FLOW_DOMAIN}`)
      - traefik.http.routers.Flow-Log.tls=true
      - traefik.http.routers.Flow-Log.tls.certresolver=letsencrypt
      - traefik.http.services.Flow-Log.loadbalancer.server.port=80
    volumes:
      - /srv/docker/flow/config:/etc/flow
      - /srv/docker/flow/log:/data
    depends_on:
      flow-auth:
        condition: service_healthy
      deepstream:
        condition: service_healthy

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.12.2
    restart: unless-stopped
    hostname: logstash
    networks:
      - flow
    ports:
      - 10514:10514
    volumes:
      - /srv/docker/logstash/config:/usr/share/logstash/config
      - /srv/docker/logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - flow-search-8
      - flow-log
