services:
  metabase:
    image: metabase/metabase:v0.47.13
    container_name: metabase
    hostname: metabase
    restart: unless-stopped
    networks:
      - traefik
      - flow
    environment:
      - JAVA_TIMEZONE=${TZ}
      - TZ=${TZ}
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${DATABASE_USER}
      - MB_DB_PASS=${DATABASE_PASSWORD}
      - MB_DB_HOST=postgresql
    labels:
      - traefik.enable=true
      - traefik.http.routers.Metabase.entrypoints=https
      - traefik.http.routers.Metabase.rule=Host(`${METABASE_DOMAIN}`)
      - traefik.http.routers.Metabase.tls=true
      - traefik.http.routers.Metabase.tls.certresolver=letsencrypt
      - traefik.http.services.Metabase.loadbalancer.server.port=3000
    depends_on:
      - postgresql
