services:
  postgresql:
    image: postgres:16-bookworm
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    networks:
      - flow
    ports:
      - 5432:5432
    volumes:
      - ${PREFIX}/srv/docker/postgresql-16:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 256M
    user: postgres
    entrypoint: postgres -c jit=off -c max_connections=2000 -c max_worker_processes=8 -c max_parallel_workers_per_gather=0
    environment:
      - POSTGRES_PASSWORD=${DATABASE_MASTER_PASSWORD}
      - POSTGRES_USER=postgres
