services:
  postgresql:
    image: ${REPOSITORY}/postgres:9.6
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    networks:
      - flow
    ports:
      - 5432:5432
    volumes:
      - ${PREFIX}/srv/docker/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_MASTER_PASSWORD}
    logging:
      driver: loki
      options:
        loki-url: "http://10.5.118.163:3100/loki/api/v1/push"
