include:
#  - portainer/docker-compose.yml
#  - traefik/docker-compose.yml

  - metabase/docker-compose.yml
#  - grafana/docker-compose.yml

services:
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    name: traefik
  flow:
    name: flow
