services:
  flow-access:
    container_name: flow-access
    image: ${REPOSITORY}/flow-access:${FLOW_VERSION}
    hostname: flow.access
    restart: unless-stopped
    networks:
      - flow
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.Flow-Access.entrypoints=https
      - traefik.http.routers.Flow-Access.rule=PathPrefix(`/api/onapi/2.3`) && Host(`${ACCESS_DOMAIN}`)
      - traefik.http.routers.Flow-Access.tls=true
      - traefik.http.services.Flow-Access.loadbalancer.server.port=8080
      - traefik.http.routers.Flow-Access.tls.certresolver=letsencrypt
      - traefik.http.routers.Flow-Access.service=Flow-Access
      - traefik.http.routers.Flow-Access.middlewares=ask-opa@file
#      - traefik.http.routers.Flow-Access-Portal.entrypoints=https
#      - traefik.http.routers.Flow-Access-Portal.rule=( PathPrefix(`/api/portal`) || PathPrefix(`/portal`) ) && Host(`${PORTAL_DOMAIN}`)
#      - traefik.http.routers.Flow-Access-Portal.tls=true
#      - traefik.http.services.Flow-Access-Portal.loadbalancer.server.port=8081
#      - traefik.http.routers.Flow-Access-Portal.service=Flow-Access-Portal
#      - traefik.http.routers.Flow-Access-Portal.tls.certresolver=letsencrypt
    environment:
      - PORTALS_DISABLED=1
      - NA_INTEGRATION=0
      - FLOW_INTEGRATION=1
      - PASSWORD_RECOVERY_ENABLED=1
      - TICKETS_ENABLED=1
      - BILLING_EXPORT_ENABLED=1
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
      - SAVE_IF_EXISTS=This address is correct
      - SAVE_IF_EMPTY=Create new address
      - SAVE_IF_CHANGED=Update address connection
      - WRONG_ADDRESS=\\u003cul\\u003e \\u003cli\\u003eÄr jag på rätt adress??\\u003c/li\\u003e \\u003cli\\u003eÄr insvetstning gjord enlig utskarvningsplan(färgordning, tub, etc…)?\\u003c/li\\u003e \\u003cli\\u003eÄr adressen terminerad i rätt ODF-port i nod?\\u003c/li\\u003e\n\\u003cli\\u003eÄr inpatchning till switch korrekt enligt panelkort?\\u003c/li\\u003e \\u003c/ul\\u003e
      - SEARCH_ENABLED=1
      - ENTER_MANUALLY_ENABLED=0
      - CHECK_FIBER_OUTLET_ENABLED=0
      - PORTAL_URL=/portal/
      - INFORMATION_URL=/info
      - ACTIVATION_URL=
      - REDIRECT_AFTER_INSTALL_ENABLED=0
      - PORTAL_LABELS=Published
      - INSTALLATION_EXCLUDE_LABEL=
      - INSTALLATION_EXCLUDE_VALUE=Blocked
    volumes:
      - /srv/docker/flow/config:/etc/flow

  # flow-gui-access:
  #   container_name: flow-gui-access
  #   image: ${REPOSITORY}/flow-gui-access:${FLOW_VERSION}
  #   restart: unless-stopped
  #   networks:
  #     - flow
  #     - haproxy
  #   environment:
  #     #- SERVICE_PORTS=80
  #     - VIRTUAL_HOST=http://access.*,https://access.*
  #     - FORCE_SSL=true
  #     - VIRTUAL_HOST_WEIGHT=1
  #     - TZ=${TZ}
  #   volumes:
  #     - /srv/docker/flow/config:/etc/flow
  #     - /srv/docker/flow/gui:/data
