services:
  flow-auth:
    container_name: flow-auth
    hostname: flow.auth
    restart: unless-stopped
    image: ${REPOSITORY}/flow-auth:${FLOW_VERSION}
    networks:
      - flow
      - traefik
    # ports:
    #   - 8000:8000
    environment:
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
      # - EXCLUDE_PORTS=8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.Flow-Auth.entrypoints=https
      - traefik.http.routers.Flow-Auth.rule=PathPrefix(`/api/auth`) && Host(`${FLOW_DOMAIN}`)
      - traefik.http.routers.Flow-Auth.tls=true
      - traefik.http.routers.Flow-Auth.tls.certresolver=letsencrypt
      - traefik.http.services.Flow-Auth.loadbalancer.server.port=80
    volumes:
      - /srv/docker/flow/config:/etc/flow
      - /srv/docker/flow/auth:/data
    healthcheck:
      test: nc localhost 8000
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
 #   healthcheck:
 #     disable: true
    depends_on:
      postgresql:
        condition: service_started
      deepstream:
        condition: service_healthy
