services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:latest
    hostname: rethinkdb
    restart: unless-stopped
    networks:
      - flow
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - /srv/docker/rethinkdb:/data
    logging:
      driver: loki
      options:
        loki-url: "http://10.5.118.163:3100/loki/api/v1/push"
