services:
  prometheus:
    image: prom/prometheus:v2.22.2
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    networks:
      - flow
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.Prometheus.entrypoints=prometheus
      - traefik.http.routers.Prometheus.rule=Host(`${FLOW_DOMAIN}`)
      - traefik.http.routers.Prometheus.tls=true
      - traefik.http.routers.Prometheus.tls.certresolver=letsencrypt
      - traefik.http.services.Prometheus.loadbalancer.server.port=9090
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle --storage.tsdb.retention=${PROMETHEUS_RETENTION} --storage.tsdb.path /prometheus --web.enable-admin-api
    volumes:
      - /srv/docker/flow/config/prometheus:/etc/prometheus
      - /srv/docker/flow/monitoring/prometheus:/prometheus
      - /srv/docker/flow/monitoring:/etc/file_sd_configs

  # prometheus-snmp-exporter:
  #   image: ${REPOSITORY}/snmp_exporter:${FLOW_VERSION}
  #   container_name: prometheus-snmp-exporter
  #   restart: unless-stopped
  #   ports:
  #     - 9116:9116
  #   networks:
  #     - flow
  #   volumes:
  #     - /srv/docker/flow/config/snmp_exporter:/etc/snmp_exporter

  # prometheus-blackbox-exporter:
  #   image: prom/blackbox-exporter
  #   container_name: prometheus-blackboxexporter
  #   hostname: prometheus.blackboxexporter
  #   restart: unless-stopped
  #   ports:
  #     - 9115:9115
  #   networks:
  #     - flow
  #   volumes:
  #     - /srv/docker/flow/config/blackbox_exporter:/etc/blackbox_exporter
  #     - /srv/docker/flow/monitoring/blackbox_exporter:/blackbox_exporter

  # prometheus-alertmanager:
  #   image: prom/alertmanager:v0.26.0
  #   container_name: prometheus-alertmanager
  #   hostname: prometheus.alertmanager
  #   restart: unless-stopped
  #   ports:
  #     - 9093:9093
  #   networks:
  #     - flow
  #   volumes:
  #     - /srv/docker/flow/config/alertmanager:/etc/alertmanager
  #     - /srv/docker/flow/monitoring/alertmanager:/alertmanager      
