services:
  flow-monitoring:
    container_name: flow-monitoring
    image: ${REPOSITORY}/flow-monitoring:${FLOW_VERSION}
    hostname: flow.monitoring
    restart: unless-stopped
    networks:
      - flow
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.Flow-Monitoring.entrypoints=https
      - traefik.http.routers.Flow-Monitoring.rule=PathPrefix(`/api/monitoring`) && Host(`${FLOW_DOMAIN}`)
      - traefik.http.routers.Flow-Monitoring.tls=true
      - traefik.http.routers.Flow-Monitoring.tls.certresolver=letsencrypt
      - traefik.http.services.Flow-Monitoring.loadbalancer.server.port=80      
    environment:
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
      - MIBDIRS=$HOME/.snmp/mibs:mibs:/usr/share/snmp/mibs:$HOME/.snmp/mibs/ietf:$HOME/.snmp/mibs/iana
    volumes:
      - /srv/docker/flow/config:/etc/flow
      - /srv/docker/flow/monitoring:/data
  
#  flow-monitoring-icons:
#    container_name: flow-monitoring-icons
#    image: ${REPOSITORY}/flow-monitoring-icons:2024.2.0
#    hostname: flow.monitoring.icons
#    restart: unless-stopped
#    networks:
#      - flow
#      - traefik
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.Flow-Monitoring-Icons.entrypoints=flow-monitoring-icons
#      - traefik.http.routers.Flow-Monitoring-Icons.rule=Host(`${FLOW_DOMAIN}`)
#      - traefik.http.routers.Flow-Monitoring-Icons.tls=true
#      - traefik.http.routers.Flow-Monitoring-Icons.tls.certresolver=letsencrypt
#      - traefik.http.services.Flow-Monitoring-Icons.loadbalancer.server.port=8002
#    environment:
#      - TZ=${TZ}
#      - JAVA_OPTS=${JAVA_OPTS}
#    volumes:
#      - /srv/docker/flow/config:/etc/flow
#      - /srv/docker/flow/monitoring:/data
  
#  flow-monitoring-prometheusalertmanager:
#    container_name: flow-monitoring-prometheusalertmanager
#    image: ${REPOSITORY}/flow-monitoring-prometheusalertmanager:2024.2.0
#    hostname: flow.monitoring.prometheusalertmanager
#    restart: unless-stopped
#    networks:
#      - flow
#      - traefik
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.Flow-Monitoring-PrometheusAlertManager.entrypoints=flow-monitoring-prometheusalertmanager
#      - traefik.http.routers.Flow-Monitoring-PrometheusAlertManager.rule=Host(`${FLOW_DOMAIN}`)
#      - traefik.http.routers.Flow-Monitoring-PrometheusAlertManager.tls=true
#      - traefik.http.routers.Flow-Monitoring-PrometheusAlertManager.tls.certresolver=letsencrypt
#      - traefik.http.services.Flow-Monitoring-PrometheusAlertManager.loadbalancer.server.port=8003
#    environment:
#      - TZ=${TZ}
#      - JAVA_OPTS=${JAVA_OPTS}
#    volumes:
#      - /srv/docker/flow/config:/etc/flow
#      - /srv/docker/flow/monitoring:/data      
