services:
  flow-inventory:
    container_name: flow-inventory
    image: ${REPOSITORY}/flow-inventory:${FLOW_VERSION}
    hostname: flow.inventory
    restart: unless-stopped
    networks:
      - flow
      - traefik
    environment:
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.Flow-Inventory.entrypoints=https
      - traefik.http.routers.Flow-Inventory.rule=PathPrefix(`/api/inventory`) && Host(`${FLOW_DOMAIN}`)
      - traefik.http.routers.Flow-Inventory.tls=true
      - traefik.http.routers.Flow-Inventory.tls.certresolver=letsencrypt
      - traefik.http.services.Flow-Inventory.loadbalancer.server.port=80
    volumes:
      - /srv/docker/flow/config:/etc/flow
      - /srv/docker/flow/inventory:/data
    depends_on:
      flow-auth:
        condition: service_started
      deepstream:
        condition: service_healthy