services:
  installation:
    container_name: installation
    # Revert to 2023.2.3 for fiber optic values
    image: install.maintrac.se/release/installation:2023.2.3
    hostname: flow.installation
    restart: unless-stopped
    networks:
      - flow
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.Installation.entrypoints=https
      - traefik.http.routers.Installation.rule=PathPrefix(`/api/portal`) && Host(`${PORTAL_DOMAIN}`)
      - traefik.http.routers.Installation.tls=true
      - traefik.http.services.Installation.loadbalancer.server.port=8081
    environment:
      - PASSWORD_RECOVERY_ENABLED=1
      - TICKETS_ENABLED=0
      - BILLING_EXPORT_ENABLED=0
      - NA_INTEGRATION=0
      - FLOW_INTEGRATION=1
      - SAVE_IF_EXISTS=This address is correct
      - SAVE_IF_EMPTY=Create new address
      - SAVE_IF_CHANGED=Update address connection
      - WRONG_ADDRESS=\\u003cul\\u003e \\u003cli\\u003eÄr jag på rätt adress??\\u003c/li\\u003e \\u003cli\\u003eÄr insvetstning gjord enlig utskarvningsplan(färgordning, tub, etc…)?\\u003c/li\\u003e \\u003cli\\u003eÄr adressen terminerad i rätt ODF-port i nod?\\u003c/li\\u003e\n\\u003cli\\u003eÄr inpatchning till switch korrekt enligt panelkort?\\u003c/li\\u003e \\u003c/ul\\u003e
      - SEARCH_ENABLED=0
      - ENTER_MANUALLY_ENABLED=0
      - CHECK_FIBER_OUTLET_ENABLED=0
      - PORTAL_URL=/portal/
      - INFORMATION_URL=/info
      - ACTIVATION_URL=
      - REDIRECT_AFTER_INSTALL_ENABLED=0
      - PORTAL_LABELS=Published
      - INSTALLATION_EXCLUDE_LABEL=
      - INSTALLATION_EXCLUDE_VALUE=Blocked
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    volumes:
      - /srv/docker/flow/config:/etc/flow

  installation-gui:
    container_name: installation-gui
    image: install.maintrac.se/release/installation-gui:2024.1.0
    restart: unless-stopped
    networks:
      - flow
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.Installation-GUI.entrypoints=https
      - traefik.http.routers.Installation-GUI.rule=Host(`${PORTAL_DOMAIN}`)
      - traefik.http.routers.Installation-GUI.tls=true
      - traefik.http.services.Installation-GUI.loadbalancer.server.port=80
    environment:
       - TZ=${TZ}
    volumes:
       - /srv/docker/flow/config:/etc/flow
       - /srv/docker/flow/gui:/data
