services:
  flow-customer:
    container_name: flow-customer
    image: ${REPOSITORY}/flow-customer:${FLOW_VERSION}
    hostname: flow.customer
    restart: unless-stopped
    networks:
      - flow
      - traefik
    environment:
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.Flow-Customer.entrypoints=https
      - traefik.http.routers.Flow-Customer.rule=PathPrefix(`/api/customer`) && Host(`${FLOW_DOMAIN}`)
      - traefik.http.routers.Flow-Customer.tls=true
      - traefik.http.services.Flow-Customer.loadbalancer.server.port=80
    volumes:
      - /srv/docker/flow/config:/etc/flow
      - /srv/docker/flow/customer:/data
    depends_on:
      flow-auth:
        condition: service_started
      deepstream:
        condition: service_healthy