services:
  flow-address:
    container_name: flow-address
    image: ${REPOSITORY}/flow-address:${FLOW_VERSION}
    hostname: flow.address
    restart: unless-stopped
    networks:
      - flow
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.Flow-Address.entrypoints=https
      - traefik.http.routers.Flow-Address.rule=PathPrefix(`/api/address`) && Host(`${FLOW_DOMAIN}`)
      - traefik.http.routers.Flow-Address.tls=true
      - traefik.http.routers.Flow-Address.tls.certresolver=letsencrypt
      - traefik.http.services.Flow-Address.loadbalancer.server.port=80
    environment:
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    volumes:
      - /srv/docker/flow/config:/etc/flow
      - /srv/docker/flow/address:/data
    depends_on:
      flow-auth:
        condition: service_started
      deepstream:
        condition: service_healthy
    logging:
      driver: loki
      options:
        loki-url: "http://10.5.118.163:3100/loki/api/v1/push"
