services:
  flow-product:
    container_name: flow-product
    image: ${REPOSITORY}/flow-product:${FLOW_VERSION}
    hostname: flow.product
    restart: unless-stopped
    networks:
      - flow
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.Flow-Product.entrypoints=https
      - traefik.http.routers.Flow-Product.rule=PathPrefix(`/api/product`) && Host(`${FLOW_DOMAIN}`)
      - traefik.http.routers.Flow-Product.tls=true
      - traefik.http.routers.Flow-Product.tls.certresolver=letsencrypt
      - traefik.http.services.Flow-Product.loadbalancer.server.port=80      
    environment:
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    volumes:
      - /srv/docker/flow/config:/etc/flow
      - /srv/docker/flow/product:/data
    depends_on:
      flow-auth:
        condition: service_started
      deepstream:
        condition: service_healthy
